language: python
dist: xenial
sudo: true
python:
  - "3.6"
# Activate addons when integration tests will be
# implemented with Tartiflette
# addons:
#   apt:
#     packages:
#       - build-essential
#       - clang
#       - cmake
#       - bison
#       - flex
#
# Compliant with Gazr Specification
# https://gazr.io
# https://github.com/dailymotion/gazr
# make style | test-unit | test-functional | init
script:
  - make test-unit
  - make test-functional
  - make style
  - make complexity
cache: pip
install:
- make init
- pip install -e .[test]
deploy:
  provider: pypi
  user: dailymotion
  password:
    secure: "lvwOKPdsFwO9QWpG5Eu423XiYms4hfP8DMhkH2Ku1ivZcES2NZ0FRYrJ0UyCSx9A1k9xfSYjRDe0KxMTPo4HwJjMhl/3JDO7OrI5NqpJiNVG6NQ8djBc+gwj5epugJ6duXe1MPXaNs3Ppo2EOwoslOJDl711YFaBXZsGfQvQ3Z22LyWVQ/QzWth4IzHkI3E0fOg7sPvI83hlhI0Pzfp5DdX6byoQssr65Hs1HvfEbWS3VgA+xZ1lznXMV0Dwl3o8aY2+FbOM8vUvR9HX9Rfm4t1/vOpuKF/9fciJUsCd42FnRayCjt1HsNKW0+EtkaV++oqzB7Dop0BasCc+MGx66iGFIrrAb8HIuIMwR1lMkJr6r9cbQpR7irkuCmMW3O1g52rLM1ky3vBhTzpodk4E9LQ96M9rVxPSez+nXvp94MNk9P6KdqYmgWCKym/kyrXPQrR0vq6URigtGl54HwzvxZfQaLxIPIbPRGqygS282ewzHIEcPm5cJQB1EZb/ZbK1xju7LNzkL933YE0u5kU93/5h15Q0QWo28umo4dhJWH3g47rSqYjnapJwHrj1+yJpjqR3zalLVJbA/H+VmAiG3vy0oJ10nb8SXsFkcN9KcYC84GVR5cvn3UHnYYhMg2x//t8kmY1J4AU8qKk2xipmN2uEAC9ff2SqwnqMIPEQGh4="
  on:
    branch: master
