version: "3"

services:
  app:
    build: .
    ports:
      - 8090:8090
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - ns

  redis:
    image: "redis:alpine"
    networks:
      - ns

networks:
  ns:
    driver: bridge
